### PR TITLE
Adding Leap and CDT version selector

### PR DESCRIPTION
**Pull request by mikelik**
If user will run `dune --leap` or `dune --cdt` without version then list of available options will be displayed like on example below:
```
mikel@msi:~/repo/DUNE$ ./dune --leap 
Available Leap versions:
1) v3.2.1
2) v3.1.4
3) v3.2.0
4) v3.2.0-rc2
5) v3.1.3
6) v3.2.0-rc1
7) v3.1.2
8) v3.1.1
9) v3.1.0
10) v3.1.0-rc4
Enter which version you want to choose [1,10]? 1
```

### CODE REVIEW

**Review by jolly-fellow — APPROVED** [review]

**Review by larryk85 — APPROVED** [review]

**Review by ScottBailey — CHANGES_REQUESTED** [review]
As part of my review, I ran the tests to check for regressions. `tests/test_help.py` fails, otherwise this LGTM. Since this PR modifies args, it would be appropriate to fix this test here.

The intent of the initial test was to ensure that dune has a callable help, not necessarily that it was specific text. My suggestion is to change the test's search text to something simple, maybe just search for `usage: dune [-h]` and ensure `dune --help` returns success (zero). This would meet the requirement to have a test for the help command and ensure that future changes wont trip us up.

**Comment by mikelik** [comment]
@ScottBailey can you chat what fails in your case?
On my ubuntu as well as in CI it runs fine: https://github.com/AntelopeIO/DUNE/actions/runs/4222426365/jobs/7330913715
```
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/runner/work/DUNE/DUNE
collected 25 items

tests/test_all_options_tested.py s                                       [  4%]
(...)
tests/test_help.py ..                                                    [ 28%]
(...)
tests/test_wallet.py ..                                                  [100%]

================== 24 passed, 1 skipped in 314.17s (0:05:14) ===================
```

**Comment by mikelik** [comment]
> @ScottBailey can you chat what fails in your case? On my ubuntu as well as in CI it runs fine: https://github.com/AntelopeIO/DUNE/actions/runs/4222426365/jobs/7330913715

It occurred that in Python3.11 the output is "options:" instead of "options arguments:".

**Review by ScottBailey — APPROVED** [review]
Tests now pass with python-3.11. Thanks!

**Pull request merged**
